You can use the `sys.dm_db_tuning_recommendations` dynamic management view (DMV) to check for Automatic Plan Correction (APRC) recommendations for a specific query. This DMV provides detailed information about tuning recommendations, including the reason for the recommendation and its current state.

### Query to Check APRC Status

Here is a T-SQL query you can use to check the APRC status for a given `query_id`:

```sql
SELECT
    name,
    reason,
    score,
    JSON_VALUE(details, '$.implementationDetails.script') AS script,
    details.*
FROM
    sys.dm_db_tuning_recommendations
CROSS APPLY
    OPENJSON(details, '$.planForceDetails')
    WITH (
        [query_id] INT '$.queryId',
        regressed_plan_id INT '$.regressedPlanId',
        last_good_plan_id INT '$.recommendedPlanId'
    ) AS details
WHERE
    JSON_VALUE(STATE, '$.currentValue') = 'Active'
    AND query_id = <your_query_id>;
```

Replace `<your_query_id>` with the actual ID of the query you want to investigate.

### Understanding the Query and its Output

This query retrieves information from the `sys.dm_db_tuning_recommendations` DMV and filters for active recommendations for the specified `query_id`. Here's a breakdown of the key columns in the output:

| Column | Description |
| --- | --- |
| **name** | Unique name of the recommendation. |
| **reason** | Reason why this recommendation was provided. |
| **score** | Estimated value/effect of this recommendation on a 0-100 scale (the larger the better). |
| **script**| The T-SQL script that can be executed to force the recommended plan. |
| **query\_id** | The ID of the regressed query. |
| **regressed\_plan\_id** | The ID of the regressed plan. |
| **last\_good\_plan\_id** | The ID of the plan that is recommended to be forced. |

### How APRC Works

Automatic Plan Correction is a feature of the Automatic Tuning in SQL Server and Azure SQL that identifies and corrects query execution plan regressions. It relies on the Query Store to be enabled on the database to track query performance over time. When a query's performance regresses significantly, APRC can automatically force the last known good plan to stabilize performance.

APRC is enabled at the database level. You can check if it is enabled for your database with the following query:

```sql
SELECT * FROM sys.database_automatic_tuning_options;
```

The `sys.dm_db_tuning_recommendations` DMV provides the recommendations generated by the automatic tuning feature. This information is updated when the database engine identifies a potential query performance regression and is not persisted after a database engine restart.

The `state` column in this DMV can have several values, including:

*   **Active**: The recommendation is active and has not yet been applied.
*   **Verifying**: The recommendation has been applied, and the system is verifying its effectiveness.
*   **Success**: The recommendation was successfully applied.
*   **Reverted**: The recommendation was reverted because there were no significant performance gains.

By querying `sys.dm_db_tuning_recommendations`, you can gain insight into how APRC is working for your queries and manually apply or revert recommendations as needed.