---------Syntax-------------

EXEC PublisherDatabase.sys.sp_dropsubscription

 @publication = N'Pub_Name',

 @article = N'article_name',

 @subscriber = N'instance2_name',

 @destination_db = N'db_name' ;

GO

EXEC PublisherDatabase.sys.sp_droparticle

 @publication = N'Pub_Name',

 @article = N'article_name',

 @force_invalidate_snapshot = 1 ;

GO




--Example:

EXEC CentralRepository_PD.sys.sp_dropsubscription

 @publication = N'Practice_Replication',

 @article = N'CentralRepository_Associate_NID',

 @subscriber = N'CTSC01135085001',

 @destination_db = N'Practice' ;

GO

EXEC CentralRepository_PD.sys.sp_droparticle

 @publication = N'Practice_Replication',

 @article = N'CentralRepository_Associate_NID',

 @force_invalidate_snapshot = 1 ;

GO




-- Reference: https://www.sqlservercentral.com/forums/topic/remove-article-from-existing-publication-does-it-require-a-new-snapshot

/*According to this article http://technet.microsoft.com/en-us/library/ms173832(SQL.90).aspx it says that setting @force_invalidate_snapshot = 1 will allow the proc to complete even though the action will invalidate the existing snapshot. That sounds a lot like accepting the warning generated by the GUI. Do you know if they're related?

--[ @force_invalidate_snapshot = ] force_invalidate_snapshot

--Acknowledges that the action taken by this stored procedure may invalidate an existing snapshot. force_invalidate_snapshot is a bit, with a default of 0.

0 specifies that changes to the article do not cause the snapshot to be invalid. If the stored procedure detects that the change does require a new snapshot, an error occurs and no changes are made.

1 specifies that changes to the article may cause the snapshot to be invalid, and if there are existing subscriptions that would require a new snapshot, gives permission for the existing snapshot to be marked as obsolete and a new snapshot generated.  */