CREATE ROLE "OneC_4681_Agency" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'AgencyaTs@Nonprod26';

GRANT db_datareader TO "OneC_4681_Agency";
COMMENT ON ROLE "OneC_4681_Agency" IS 'ATS_Agency Schema';
GRANT "OneC_4681_Agency" TO postgres WITH ADMIN OPTION;


CREATE ROLE "OneC_4681_Recruiter" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'RecruiteraTs@Nonprod26';

GRANT db_datareader TO "OneC_4681_Recruiter";
COMMENT ON ROLE "OneC_4681_Recruiter" IS 'ATS_Agency Schema';
GRANT "OneC_4681_Recruiter" TO postgres WITH ADMIN OPTION;



CREATE ROLE "OneC_4681_Requisition" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'RequisitionaTs@Nonprod26';

GRANT db_datareader TO "OneC_4681_Requisition";
COMMENT ON ROLE "OneC_4681_Requisition" IS 'ATS_Agency Schema';
GRANT "OneC_4681_Requisition" TO postgres WITH ADMIN OPTION;

grant "OneC_4681_Recruiter","OneC_4681_Requisition","OneC_4681_Agency" to "npgke-devops-serviceacc@cb0104074a-citnonprod-gc.iam","nonproddb-devops-sa@cb0104074a-citnonprod-gc.iam";


GRANT CONNECT, TEMPORARY ON DATABASE "OneC_4681" TO "OneC_4681_Agency";

GRANT TEMPORARY, CONNECT ON DATABASE "OneC_4681" TO "OneC_4681_Requisition";

GRANT TEMPORARY, CONNECT ON DATABASE "OneC_4681" TO "OneC_4681_Recruiter";

GRANT usage ON SCHEMA "ATS_Agency" TO "OneC_4681_Agency";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Agency"
GRANT select ON TABLES TO "OneC_4681_Agency";

--ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Agency"
--GRANT usage ON SEQUENCES TO "OneC_4681_Agency";

--ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Agency"
--GRANT EXECUTE ON FUNCTIONS TO "OneC_4681_Agency";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Agency"
GRANT USAGE ON TYPES TO "OneC_4681_Agency";

----------------------
GRANT usage ON SCHEMA "ATS_Recruiter" TO "OneC_4681_Recruiter";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Recruiter"
GRANT select ON TABLES TO "OneC_4681_Recruiter";

--ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Recruiter"
--GRANT usage ON SEQUENCES TO "OneC_4681_Recruiter";

--ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Recruiter"
--GRANT EXECUTE ON FUNCTIONS TO "OneC_4681_Recruiter";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Recruiter"
GRANT USAGE ON TYPES TO "OneC_4681_Recruiter";

------------
GRANT usage ON SCHEMA "ATS_Requisition" TO "OneC_4681_Requisition";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Requisition"
GRANT select ON TABLES TO "OneC_4681_Requisition";

--ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Requisition"
--GRANT ALL ON SEQUENCES TO "OneC_4681_Requisition";

--ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Requisition"
--GRANT EXECUTE ON FUNCTIONS TO "OneC_4681_Requisition";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "ATS_Requisition"
GRANT USAGE ON TYPES TO "OneC_4681_Requisition";
