REVOKE ALL ON DATABASE og_db FROM PUBLIC;


ALTER DEFAULT PRIVILEGES FOR ROLE sec_admin_user
    
REVOKE ALL ON TABLES FROM test_role;
REVOKE ALL ON SCHEMA public FROM "test_maintenanceUser";

ALTER DEFAULT PRIVILEGES FOR ROLE db_owner IN SCHEMA public
  
REVOKE ALL ON TABLES FROM "DBReaderTool";

